[package]
name = "sudoku-solver"
version = "0.1.0"
authors = ["Christian Tamblyn <ctamblyn76@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "solver_benchmarks"
harness = false

[dependencies]
bit-iter = "0.1"
